# Node.js

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'Snyk_Token'
    testType: 'app'
    monitorWhen: 'never'
    failOnIssues: true
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'Snyk_Token'
    testType: 'app'
    monitorWhen: 'never'
    failOnIssues: true
    additionalArguments: '--code'