# Node.js

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: 
    sudo npm install -g snyk
    sudo snyk auth $(Snyk_Token)
    sudo snyk code test --fail-on=all
  displayName: 'snyk SAST'


