# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'Snyk_Token'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: true
    projectName: 'tess-snyk/juice-shop'
    organization: 'a49e7d5e-8597-43a7-84ea-2cb3588fedb3'
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
